try:
    raise NameError
except NameError:
    print("something wrong")
 
print("after exception....")
